### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by riodda** [Eleven-Trading/TradeNote#1]
Hi, i run into this repo and i really found it interesting. I'm developing a small trading bot for alpaca.markets and currently on alpaca one of the big miss is a trading journal, therefore I wonder if I can feed your trading journal from my trading bot (python bot) trough an api or trough the database directly.
Thanks !

**Comment by 7aklhz** [comment]
Hi. The repo has been designed to use Parse.com and thereby a mongodb database. As such, you could adapt the code to insert data directly to the database. 

I actually have a custom code myself to inject certain things directly into my mongodb.

**Comment by riodda** [comment]
Thanks, will have a look to parse.com, i'm not a black belt of php or node js if your code is sharable of course will help

**Comment by 7aklhz** [comment]
Code is open source so take a look at the repo.
