### ISSUE TITLE
Discord Link Invalid

### ISSUE THREAD

**Issue by natrlhy** [Eleven-Trading/TradeNote#103]
I wanted to join your Discord server but the links to join are invalid. Can a new one be generated so one can join the server?
Thanks!

**Comment by 7aklhz** [comment]
can you tell me which one is invalid because I clicked on all of them and they work. Just in case, here is the link : https://discord.gg/ZbHekKYb85

**Comment by natrlhy** [comment]
I'm using that link. In Firefox it opens a tab and displays this:

![image](https://github.com/user-attachments/assets/e0b393a5-0d89-4610-aa39-a007ebd511e9)

I also have the Discord app running on my PC

**Comment by natrlhy** [comment]
I had to logout and back in on discord on my browser. I'm in now!
