### ISSUE TITLE
[Documentation] MongoDB compass link point to parse community

### ISSUE THREAD

**Issue by cderv** [Eleven-Trading/TradeNote#105]
I did not find the doc site sources so here is an issue for the feedback

In there: https://tradenote.co/database.html#viewing-data

````html
<a href="https://github.com/parse-community" title="MongoDB Compass" target="_blank" rel="noreferrer">MongoDB Compass</a>
````

The link ☝️ is for MongoDB Compass but points to https://github.com/parse-community 

Shouldn't it be https://www.mongodb.com/products/tools/compass instead ? 

The parse community seems to be for the other tool mentioned : https://github.com/parse-community/parse-dashboard

**Comment by 7aklhz** [comment]
Thank you. Corrected
