### ISSUE TITLE
[question] - No manual entry ?

### ISSUE THREAD

**Issue by bengivre** [Eleven-Trading/TradeNote#107]
Hello, 
Just wanted to make sure I did not miss it. 

It seems that **TradeNote** is only made for people to **import** trades history from brokers right?
I was expecting a way to add trades manually to journal them as they go, but that is not what is TradeNote about? 

Thanks :)

**Comment by 7aklhz** [comment]
Correct. The only way to add trades "manually" is to use the csv template. But you can only import a date once so you have to first fill out the csv completely before importing.

**Comment by 7aklhz** [comment]
Correct. The only way to add trades "manually" is to use the csv template. But you can only import a date once so you have to first fill out the csv completely before importing.
