### ISSUE TITLE
Enhance Playbook Functionality: Criteria Tracking and Profit Analysis for Each Trade

### ISSUE THREAD

**Issue by zaeemone5** [Eleven-Trading/TradeNote#110]
Description
Feature Request:
I’d like to propose an enhancement to the Playbook feature in Trade Note to improve its functionality and usability for traders.

Details
Playbook Criteria Tagging:

Add the ability to tag each trade with the criteria from the associated Playbook.
Display the tagged criteria directly on each trade for quick reference.
Criteria Performance Analysis:

Introduce analytics to track:
Which criteria were respected in each trade.
How each criterion contributes to overall profitability.
Which criteria are negatively affecting profitability.
Visualization:

Provide visual charts or tables to highlight:
Profitable vs. unprofitable criteria.
Success rates of trades meeting specific criteria.
Benefits
Improved Decision-Making: Traders can identify which criteria work best and refine their strategies accordingly.
Enhanced Learning: Helps traders learn from both successful and unsuccessful trades by analyzing key factors.
Efficiency: Saves time by consolidating trade data and insights in one place.
Example Use Case
A trader reviews their trades and sees that a specific criterion (e.g., "Price Action Confirmation") has a high success rate.
Conversely, they notice that another criterion (e.g., "Breakout Strategy") leads to losses more often than not.
This insight allows them to focus on high-performing strategies and adjust or eliminate underperforming ones.
Additional Notes
This feature could be implemented as an optional module or dashboard within the Playbook section.
Filters could be added to sort trades by specific criteria for deeper analysis.

**Comment by 7aklhz** [comment]
I have a long term objective to improve the playbook part which would inlcude something like you mentioned. Stay tuned via Discord channel where I post updates.
