### ISSUE TITLE
Check entry and exit Timestamp to mark the trade with the right operation (long in / out // short in / out)

### ISSUE THREAD

**Issue by Canonius** [Eleven-Trading/TradeNote#16]
![image](https://user-images.githubusercontent.com/50411138/230888767-d557fe9f-1946-401d-b55f-421f14e92e7b.png)
![image](https://user-images.githubusercontent.com/50411138/230888791-976d6926-0534-47c6-9b6a-349d59cc5b03.png)

**Comment by 7aklhz** [comment]
Thanks. This should no longer be the issue with v9.3.4
