### ISSUE TITLE
Thumbs-UP is creating an empty table data cell <td></td>

### ISSUE THREAD

**Issue by Canonius** [Eleven-Trading/TradeNote#22]
![image](https://user-images.githubusercontent.com/50411138/231972494-0cb7ccd2-d54c-4859-b5c9-014404bfdcd6.png)

![image](https://user-images.githubusercontent.com/50411138/231972214-07c90d24-35fb-44c4-a228-eef164a55933.png)

**Comment by 7aklhz** [comment]
Ok, this is now corrected in v9.8.3
