### ISSUE TITLE
"Group by Symbol" overview - Symbol-count (left)  not matching line-count (right)

### ISSUE THREAD

**Issue by Canonius** [Eleven-Trading/TradeNote#25]
![image](https://user-images.githubusercontent.com/50411138/236896124-fa9f1fb1-0e6b-42f8-9004-cf626214dab8.png)

**Comment by 7aklhz** [comment]
With big number of symbols it will automatically be stacked but I have made 2 improvements in v18.18.1
1- I have removed symbols that are open / swing trades to simplify the list
2- on mouse hover, you can see the name of the symbol
