### ISSUE TITLE
BUG: Adding Pattern/Mistake to daily trade afterwards is removing screenshot

### ISSUE THREAD

**Issue by Canonius** [Eleven-Trading/TradeNote#40]
After adding notes and screenshot to one trade 

1. add screenshot
2. add drawings
3. add Notes
4. save & close
5. open this trade again
6. add mistake/pattern
7. save & close
8. screenshot icon disappears in daily - trades tab - table
9. open this trade - no screenshot
10. remove mistake/pattern 
11. save & close
12. screenshot appers again
13. notes disappears in this trade

**Comment by 7aklhz** [comment]
This has been corrected in 11.3.10
