### ISSUE TITLE
Error while importing trade csv template

### ISSUE THREAD

**Issue by chengwah1** [Eleven-Trading/TradeNote#43]
![Screenshot 2023-05-21 012947](https://github.com/Eleven-Trading/TradeNote/assets/12405234/1815daa8-78d7-4ec7-8cc8-2edc6a914cbb)

[template2.csv](https://github.com/Eleven-Trading/TradeNote/files/11522858/template2.csv)

attached csv file to reproduce.
there's error on .split() but after clicking ok, all info displayed. so im not sure what data is missing.

tradenote version 10.3.19

**Comment by 7aklhz** [comment]
I'm currently migrating the code base but will look I to it in the next week or two. 

For your information 
- glancing at your csv it seems that you have adapted the template. Usually, the split error arises when you have and additional void line. You can try to see if you have that 
- what broker are you using ? I can eventually add your broker to the list 
- these type of errors are somewhat easier to discuss and test over a chat so if you can connect via the discord channel.

**Comment by chengwah1** [comment]
Hi,
Yes there's indeed an extra row when I save it from excel in csv.
`const keys = Object.keys(this.tradesData);` has an extra index,
i'll just edit it notepad or notepad++ to remove the empty row.

what broker are you using ? I can eventually add your broker to the list
Webull but dont bother as their sister company from different country has slightly different statement.

**Comment by 7aklhz** [comment]
Ok, as you wish. 

Glad the issue got resolved. Happy journaling with TradeNote
