### ISSUE TITLE
Enlarge some screenshots in screenshot page gives blank page and error in console

### ISSUE THREAD

**Issue by Canonius** [Eleven-Trading/TradeNote#46]
![image](https://github.com/Eleven-Trading/TradeNote/assets/50411138/9f451bae-1cd0-4c06-8805-da9c5e275489)

**Comment by 7aklhz** [comment]
is this still an issue (I think we corrected this)

**Comment by Canonius** [comment]
i did not faced this issue again, seems to be fixed. Thanks
