### ISSUE TITLE
Parse dashboard seems hard to setup

### ISSUE THREAD

**Issue by krishna-vinci** [Eleven-Trading/TradeNote#5]
I installed, parse server& dashboard in AWS, local but in both, I'm only getting into the loading screen and then just blank white page..
It would be great if there is an easy and working way to set it up in your guide.
I'm asking cus I tried many guides but can't able to fix it.. I'm soo eager to use your journal but soo frustrated too from the last 3days.. haha.😄
Thanks for the work. It's soo useful for many..

update: I just need to use my exact ip instead of localhost for parse server&dashboard

**Comment by krishna-vinci** [comment]
btw its not possible to insert trades besides tradezero?

**Comment by 7aklhz** [comment]
> update: I just need to use my exact ip instead of localhost for parse server&dashboard
Great. For your information, I juste update the Readme with instruction of how to install using Docker thanks to the contribution of @barretthugh

**Comment by 7aklhz** [comment]
> btw its not possible to insert trades besides tradezero?

Correct, I have only tested using TradeZero. However, there is [example file](https://github.com/Eleven-Trading/TradeNote/blob/main/example_tradezero_file.csv) that you can update to your csv format. 

Besides, you can suggest and vote for your Platform on [Fider](https://fider.tradenote.co/). When I have enough interest, I will develop/adapt little by little to other platforms. What trading platform do you use ?
