### ISSUE TITLE
Calendar incorrect

### ISSUE THREAD

**Issue by mblanco4x4** [Eleven-Trading/TradeNote#50]
The Daily view is correct with dates/times but the Calendar view is out of whack. It shows trades occurring Fri-Tues rather than when they actually occurred, Mon-Fri.

Thanks

![Screenshot 2023-06-17 235255](https://github.com/Eleven-Trading/TradeNote/assets/77179222/6f8245ee-8831-465e-a2ed-6de02d1f7f03)

**Comment by 7aklhz** [comment]
Can you check please tel me what version you are running, what time zone your trades are in and what time zone your computer clock is ?

**Comment by mblanco4x4** [comment]
Version: tradenote:11.13.7_beta.
Trades are in New York(EST) time.
Computer is in Chicago(CST) time.

Thanks

**Comment by mblanco4x4** [comment]
Once lauched the Tradenote/TradenoteDB containers are in UTC time since there is no time zone specified in compose env variable.

**Comment by mblanco4x4** [comment]
Seems to be a problem specific to the Calendar formatting itself. In the screenshot above, last week was Jun 8th-12th when the actual week was Jun 12th-16th.

**Comment by 7aklhz** [comment]
Yes it's a cal issue, which should have been  fixed  numerous versions ago. I will have a look. For your info, if you can, it's easier to chat using the discord.

**Comment by mblanco4x4** [comment]
Thx. Yes I'm in the discord community as MB4X4.
