### ISSUE TITLE
Feature: Ability to check if running the latest version

### ISSUE THREAD

**Issue by derwin12** [Eleven-Trading/TradeNote#54]
Perhaps clicking on the current version could check to see if it is the latest release?

**Comment by 7aklhz** [comment]
Currently you can see your running version by clicking on your avatar. Then you can compare it to the tag either present in the docker hub or on GitHub. 

I would say that's the easy solution. Even more that "latest version" is not the same if you're running the docker image from docker hub (that's the latest stable version) or building form GitHub (that's the latest pushed version)
