### ISSUE TITLE
Add Function

### ISSUE THREAD

**Issue by rttr1986** [Eleven-Trading/TradeNote#58]
Can you add a function to delete the entries for the iteration date if trades already exists in DB? to load the trades multiple times in a day

**Comment by 7aklhz** [comment]
Currently there is a "function" that prevents you from uploading trades from the same date multiple times. Not sure I understand what you want exactly. Can you please rephrase ? And also explain way / What you want to achieve?

**Comment by rttr1986** [comment]
If we add trades too soon in the day and there are few trades done later, while trying to upload it doesn't allow, so if you delete existing trades for the day and upload again it would be better

**Comment by 7aklhz** [comment]
Ok, so you would like the possibility to delete (all) trades for a given day. Correct ? This is a recurring demand and I have it in the backlog. Don't have any date for development but will do it in not too long

**Comment by rttr1986** [comment]
Thanks

**Comment by 7aklhz** [comment]
I will send an update when it's done on discord. So please connect there if you wish to be updated.

**Comment by cmol1** [comment]
Thanks @7aklhz. The other limitation is if we trade with multiple accounts and want to upload the reports, you can only do it for one account as it won't let you do it for the second one as you already uploaded trades for that date, perhaps it would be good to be able to enable/disable this function or update the function so that it takes the account number/ID into account when performing the validation.

**Comment by 7aklhz** [comment]
Ah interesting use case. So indeed, I will add a check on account Again, please use Discordant if you want updates on this

**Comment by 7aklhz** [comment]
However, it works to import multiple accounts on the same import file. So if you gather the two files into one before import it will work

**Comment by cmol1** [comment]
@7aklhz Makes sense, the only thing is merging reports from MT5 can be messy if many trades are taken in a particular day, even worse if you add the trades once a week as more trades will need to be merged. Not a show stopper but it would be a nice to have. Thanks heaps.
