### ISSUE TITLE
Error when importing from TDA/TOS

### ISSUE THREAD

**Issue by oskapt** [Eleven-Trading/TradeNote#66]
When importing trades from a TOS CSV file, I get the following error:

![image](https://github.com/Eleven-Trading/TradeNote/assets/171292/e28f215e-80f1-4bea-864f-77e30ce7661c)

I generated the CSV according to the instructions in Github. 

Where can I find more information to help troubleshoot this?

**Comment by 7aklhz** [comment]
All import issues must go through the discord channel as they require often back and forth. Can you please contact me there?
