### ISSUE TITLE
getting issue on CapRover

### ISSUE THREAD

**Issue by R0bbieJ** [Eleven-Trading/TradeNote#7]
![Screenshot 2022-09-20 221517](https://user-images.githubusercontent.com/10146278/191365910-03bead1e-93de-4915-a457-48ae6632d57a.png)
![Screenshot 2022-09-20 221553](https://user-images.githubusercontent.com/10146278/191365991-99420799-30ce-499e-8fe2-08e0d2cfa921.png)

**Comment by 7aklhz** [comment]
I have not enough context. Did you first install parse via captiver too ? Is TradeNote loading ? etc

**Comment by R0bbieJ** [comment]
First installed CapRover then parse, and then deployed tradenote, site is loading up. It happens when I try to register or even login.

> I have not enough context. Did you first install parse via caprover too ? Is TradeNote loading ? etc

**Comment by 7aklhz** [comment]
Ok. I did not mention in the Readme that you have to enter variables in caprover. So, in caprover, in your TradeNote app, you have to enter two variables: PARSE_INIT and PARSE_URL. parse unit is your parse id.

**Comment by 7aklhz** [comment]
Did you make it work @R0bbieJ ?

**Comment by R0bbieJ** [comment]
> Did you make it work @R0bbieJ ?

Trying now.
looks like error changed a bit

![image](https://user-images.githubusercontent.com/10146278/191814348-df55c8cd-3a2a-4cab-bcbe-7e637f62e299.png)

**Comment by 7aklhz** [comment]
I did not mention but you need to add classes to parse. Look at this file to see what needs to be added or run the file if you know how. docker/addclasses.sh

**Comment by R0bbieJ** [comment]
> I did not mention but you need to add classes to parse. Look at this file to see what needs to be added or run the file if you know how. docker/addclasses.sh

Gotcha, not sure how to run it. 

just when deployed .tar file in caprover i seen addclasses.sh in build logs

`---> Using cache
---> c4791f0c586f
Step 7/17 : RUN npm install

---> Using cache
---> c072fd2e689d
Step 8/17 : ARG PARSE_INIT=${PARSE_INIT}

---> Using cache
---> d80628af1777
Step 9/17 : ARG PARSE_URL=${PARSE_URL}

---> Using cache
---> 5fb6fb69ec29
Step 10/17 : RUN gulp prod --PARSE_INIT $PARSE_INIT --PARSE_URL $PARSE_URL

---> Using cache
---> c7fa3cf1768c
Step 11/17 : RUN cp /usr/share/nginx/html/tmp/nginx.conf /etc/nginx/nginx.conf

---> Using cache
---> 5d001b4f7777
Step 12/17 : RUN cp -R /usr/share/nginx/html/tmp/dist/* /usr/share/nginx/html/

---> Using cache
---> d7d46d356c52
Step 13/17 : WORKDIR /usr/share/nginx/html/

---> Using cache
---> 4967e34661ea
Step 14/17 : RUN rm -r /usr/share/nginx/html/tmp

---> Using cache
---> ebda68b62ae2
Step 15/17 : RUN wget https://raw.githubusercontent.com/Eleven-Trading/TradeNote/main/docker/addclasses.sh -O /addclasses.sh

---> Using cache
---> dad9d57ab6ae
Step 16/17 : RUN chmod +x /addclasses.sh`

**Comment by R0bbieJ** [comment]
Im using https://www.digitalocean.com/ and Caprover droplet, and if i connect with putty can't find ant files haha
im pretty noob at this lol 🥇

**Comment by R0bbieJ** [comment]
could you help me thrue
 discord or smth?

**Comment by 7aklhz** [comment]
Yes, I will get back to you by tomorrow. If you join the discord it's also easier if you have any further issues.

**Comment by R0bbieJ** [comment]
> Look at this file @R0bbieJ [eab8e9f](https://github.com/Eleven-Trading/TradeNote/commit/eab8e9fd703f9a71121d5c688029fb9a27bf64cf)
> 
> You have to follow the instructions from line 52 to line 67.
> 
> I'll do a cleaner update of Readme later.

![image](https://user-images.githubusercontent.com/10146278/192337899-bf09bf1b-614d-4855-ab8a-8c8464fe6e3a.png)

Looks like im getting closer, but as you see PARSE_URL doesn't act as new url, but puts on same url forward.

**Comment by R0bbieJ** [comment]
Seems like i can register now, and it apears in parse dashboard, i get redirected after registration.
But getting black screen with. 
![image](https://user-images.githubusercontent.com/10146278/192340878-4cca431c-b709-4581-af11-fa47f28e19db.png)
