### ISSUE TITLE
Unable to import Tradovate logs

### ISSUE THREAD

**Issue by grimmolf** [Eleven-Trading/TradeNote#70]
I'm running the docker-compose.yml with the latest image and I am unable to import my tradovate logs (attached)
[Performance(2).csv](https://github.com/Eleven-Trading/TradeNote/files/13343200/Performance.2.csv). When I select the tradovate logs and commission type, it never presents a preview of the import for me to submit.

**Comment by 7aklhz** [comment]
Resolved via discord. 

For the record : to create the correct export file, please make sure to follow the instructions in the Brokers folder.
