### ISSUE TITLE
Add Feature: Automated Charts with Entry/Adds/Exit

### ISSUE THREAD

**Issue by Daerkle** [Eleven-Trading/TradeNote#73]
![image](https://github.com/Eleven-Trading/TradeNote/assets/112579143/6351686d-7aa8-4805-b6eb-d4b5674c7a08)

**Comment by Canonius** [comment]
Problem would be that most probably this 1m chart data comes not for free. The problem would be also for how long would you see that 1m data? I don't think tradingview is giving all that features for free
