### ISSUE TITLE
TDAmeritrade import fails on all imports.  Standardized Template needed that support options trades

### ISSUE THREAD

**Issue by richlysakowski** [Eleven-Trading/TradeNote#77]
I imported some data using the Template.csv example to just get SOMETHING into the database to see if import works, and it does work.  

But when I tried to import a TDAmeritrade (specifically ThinkOrSwim) CSV file, it just throws obscure error messages. The instruction say to import only the 'Trades' section of the file, but when I stripped down my file to include only the "Trades" section the import still does not work.  

I have tried many different variations of the input file for TDAmeritrade (specifically ThinkOrSwim) import instructions and nothing works.   I keep getting the error message shown in the screenshot.  

![image](https://github.com/Eleven-Trading/TradeNote/assets/9345711/599d60ec-f5e8-4645-a022-fb70109e127c)

I examined the source code in "brokers.js" and the TDA importer APPEARS recognizes the sections of a TDA-ThinkOrSwim Account Statement CSV file.  It also has some functions that process options, but no options get imported.  

Could someone provide a viable import template example for the TDA-ThinkOrSwim Account Statement CSV file import?  

We need to get the broker's Order_ID and the standard OPRA code should be used for options, or if that is not available, then the CUSIP number.  

Order_ID
OPRA_Code

The Template.CSV file does not have any options fields.  The fields below are the minimum ones expected to characterize an options trade fully.  

Expiration_Date
Strike
Option_Type (Call or Put)
Spread_Type (e.g., Vertical, Butterfly, Diagonal, Calendar, Condor, Iron Condor, etc.)
Net_Price (of a spread)
Order_Type

How do I turn on detailed logging for this application?  When I am running it using Docker, I can see the contents of the DB.log file

When I tried to import using the "Description" format, I get a different error message.  See the image below.  

![image](https://github.com/Eleven-Trading/TradeNote/assets/9345711/24205cb4-03b3-4373-a093-b3863ba371e2)

**Comment by 7aklhz** [comment]
Import issues may be complex to solve. Please use discord and I will help you there.
