### ISSUE TITLE
Feature Request: Tags for Diary/Trading Day

### ISSUE THREAD

**Issue by timbo-lino** [Eleven-Trading/TradeNote#82]
**Tags for the diary**

Why? You could assign a few tags BEFORE the trading day, e.g. about sleep quality, stress level, etc. This would allow you to see what has a positive and negative effect on your trading in the long term. 
These tags would then be valid for the entire trading day and not just for individual trades.

I think it makes sense for such tags to be assigned and entered BEFORE trading, because then there is no temptation to talk nicely or badly about certain things afterwards.

The starting conditions of the trading day can be defined via the tags

**Comment by 7aklhz** [comment]
this has been implemented
