### ISSUE TITLE
Rithmic: Part of an Auto Liquidation

### ISSUE THREAD

**Issue by bukowa** [Eleven-Trading/TradeNote#84]
```
Part of an Auto Liquidation.  Account loss (319.88) is greater than user set threshold of 300.00.
```
If you setup custom `Risk Parameters` in Rithmic you can auto liquidate your positions based on specific rules.
All positions are closed then. TradeNote doesn't respect that resulting in wrong calculation.

![exampleeessss](https://github.com/Eleven-Trading/TradeNote/assets/38087302/8eb88b89-96c7-41a1-8915-1e8e371c3838)

````csv
Working Orders
"Account","Status","Buy/Sell","Qty To Fill","Max Show Qty","Symbol","Price Type","Limit Price","Qty Filled","Qty Working","Order Number","Original Sequence Number","Current Sequence Number","User Id","Exchange Order Id","Order Update Time","Expiration Month","Stop/Trigger Price","Order Duration","Avg Fill Price","Position Disposition","IB Id","FCM Id","Create Time (CEDT)","Liquidity Indicator","Executing Venue"


Completed Orders
"Account","Status","Remarks","Buy/Sell","Qty To Fill","Max Show Qty","Symbol","Price Type","Avg Fill Price","Limit Price","Order Number","Qty Filled","Position Disposition","Application","Create Time (CEDT)","Commission","Commission Fill Rate","Account Balance"
"account1","Filled","","S","1","","6EM4","M","1.0904000","","123","AAE49YR5","AAE49YR5","account1","2024-04-09 16:21:19","1","2024-04-09 16:21:19","","","","2.36"
"account1","Filled","Part of an Auto Liquidation.  Account loss (319.88) is greater than user set threshold of 300.00.","B","1","","SIK4","M","28.38500","","124","AAE4ABSF","AAE4ABSF","account1","2024-04-09 16:21:57","1","2024-04-09 16:21:57","","","","2.31"
"account1","Filled","Part of an Auto Liquidation.  Account loss (319.88) is greater than user set threshold of 300.00.","B","1","","6EM4","M","1.0904500","","125","AAE4ABSE","AAE4ABSE","account1","2024-04-09 16:21:57","1","2024-04-09 16:21:57","","","","2.36"
````

As you can see after trying to `B` `SIK4` all my positions were closed.

https://github.com/Eleven-Trading/TradeNote/blob/5334575152f7010524fa55f634a59911489ad81f/src/utils/brokers.js#L1073

**Comment by 7aklhz** [comment]
Please use the Discord channel to review this issue with me. Looking at this export file, I do not see andy entry for SIK4, only an exit (part of the auto liquidation). Please contact me via Discord so I can try to solve this.

**Comment by bukowa** [comment]
> Please use the Discord channel to review this issue with me. Looking at this export file, I do not see andy entry for SIK4, only an exit (part of the auto liquidation). Please contact me via Discord so I can try to solve this.

Sorry my bad!
