### ISSUE TITLE
Problem with Import of MetTrader 5 report

### ISSUE THREAD

**Issue by benjberisha** [Eleven-Trading/TradeNote#95]
Hello guys

I'm now finished with the install of TradeNotes on Unraid. The connection to te DB, Login, and Upload of Screenshots works finde. Now i want to upload the Report from MetaTrader 5 (https://github.com/Eleven-Trading/TradeNote/tree/main/brokers). But i alwayws receive a error "Cannot convert undefined or null to object". Does anyone else have the same issue? I use the newest TradeNote Docker image (eleventrading/tradenote:latest) and MetaTrader 5.00 Build 4524. Unfortunately i see nothing in the log. Can anyone help.

Thank you in advance!

**Comment by 7aklhz** [comment]
Please use Discord for import issues
